services:
  - type: web
    name: pdf-rag-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: "openai/gpt-oss-120b"
      - key: OMP_NUM_THREADS
        value: "1"
      - key: MKL_NUM_THREADS
        value: "1"
      - key: TOKENIZERS_PARALLELISM
        value: "false"
